const data = [
  {
    name: "区域",
    key: "bid",
    child_key: "did",
    children: [
      { name: "不限", value: "", key: "did" },
      {
        name: "金水",
        children: [
          {
            name: "不限",
            value: "",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "东建材",
            value: "28",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "北站",
            value: "24",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "财富广场",
            value: "25",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "陈寨",
            value: "26",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "大石桥",
            value: "27",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "富田大厦",
            value: "29",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "海洋馆",
            value: "30",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "经五路",
            value: "31",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "科技市场",
            value: "32",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "绿荫广场",
            value: "33",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "庙李",
            value: "34",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "汽配大世界",
            value: "35",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "沙口路",
            value: "36",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "省人民医院",
            value: "37",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "省中医院",
            value: "38",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "双铺路",
            value: "39",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "水上乐园",
            value: "40",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "索凌路北段",
            value: "41",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "未来大厦",
            value: "42",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "文博广场",
            value: "43",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "新北站",
            value: "44",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "徐寨",
            value: "45",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "燕庄",
            value: "46",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "玉凤路",
            value: "47",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "枣庄",
            value: "48",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "紫荆山",
            value: "49",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "轻工业学院",
            value: "904",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "郑州市动物园",
            value: "905",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "柳林",
            value: "919",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "杨金路",
            value: "920",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "环球大厦",
            value: "922",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "广播电视台",
            value: "1269",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "文化北路",
            value: "1285",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "曼哈顿",
            value: "1286",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
        ],
        value: "14",
        key: "did",
        child_key: "bid",
        multipleSelect: true,
        connector: ",",
      },
      {
        name: "新密",
        children: [
          {
            name: "不限",
            value: "",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "金凤路小学",
            value: "886",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "植物园",
            value: "885",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "青屏山公园",
            value: "884",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "五四广场",
            value: "883",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "青屏市场",
            value: "882",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "西广场",
            value: "881",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
        ],
        value: "19",
        key: "did",
        child_key: "bid",
        multipleSelect: true,
        connector: ",",
      },
      {
        name: "荥阳",
        children: [
          {
            name: "不限",
            value: "",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "荥阳",
            value: "829",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
        ],
        value: "10",
        key: "did",
        child_key: "bid",
        multipleSelect: true,
        connector: ",",
      },
      {
        name: "经开",
        children: [
          {
            name: "不限",
            value: "",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "经开区",
            value: "50",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
        ],
        value: "9",
        key: "did",
        child_key: "bid",
        multipleSelect: true,
        connector: ",",
      },
      {
        name: "新郑",
        children: [
          {
            name: "不限",
            value: "",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "龙湖镇",
            value: "838",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "新郑市区",
            value: "837",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
        ],
        value: "6",
        key: "did",
        child_key: "bid",
        multipleSelect: true,
        connector: ",",
      },
      {
        name: "中牟",
        children: [
          {
            name: "不限",
            value: "",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "中牟",
            value: "58",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
        ],
        value: "2",
        key: "did",
        child_key: "bid",
        multipleSelect: true,
        connector: ",",
      },
      {
        name: "周边县市",
        children: [
          {
            name: "不限",
            value: "",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "航空港",
            value: "854",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "登封",
            value: "74",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "巩义",
            value: "75",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
        ],
        value: "4",
        key: "did",
        child_key: "bid",
        multipleSelect: true,
        connector: ",",
      },
      {
        name: "惠济",
        children: [
          {
            name: "不限",
            value: "",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "北大学城",
            value: "20",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "刘寨",
            value: "21",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "邙山",
            value: "22",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "省体育中心",
            value: "23",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
        ],
        value: "5",
        key: "did",
        child_key: "bid",
        multipleSelect: true,
        connector: ",",
      },
      {
        name: "管城",
        children: [
          {
            name: "不限",
            value: "",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "二里岗",
            value: "13",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "凤凰路",
            value: "14",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "管南区域",
            value: "15",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "客运陇海站",
            value: "16",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "南关街",
            value: "17",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "商代遗址",
            value: "18",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "世纪欢乐园",
            value: "19",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "陇海汽车站",
            value: "917",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "中原福塔",
            value: "918",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "东建材",
            value: "921",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
        ],
        value: "7",
        key: "did",
        child_key: "bid",
        multipleSelect: true,
        connector: ",",
      },
      {
        name: "高新",
        children: [
          {
            name: "不限",
            value: "",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "石佛",
            value: "11",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "新郑大",
            value: "12",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "化工路",
            value: "1469",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "莲花街",
            value: "1470",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
        ],
        value: "15",
        key: "did",
        child_key: "bid",
        multipleSelect: true,
        connector: ",",
      },
      {
        name: "二七",
        children: [
          {
            name: "不限",
            value: "",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "河医立交桥",
            value: "2",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "古玩城",
            value: "1",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "火车站",
            value: "3",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "老航院",
            value: "4",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "老郑大",
            value: "5",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "市财政局",
            value: "6",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "嵩山南路",
            value: "7",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "万客来",
            value: "8",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "鞋城",
            value: "9",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "兴华南街",
            value: "10",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "二七万达",
            value: "834",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "二七新区",
            value: "836",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "郑州客运南站",
            value: "907",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "郑州市第二人民医院",
            value: "908",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "郑州市第六人民医院",
            value: "909",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "英开体育公馆",
            value: "910",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "郑州烈士陵园",
            value: "911",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "郑州大学第一附属医院",
            value: "912",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "电力新村",
            value: "924",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
        ],
        value: "3",
        key: "did",
        child_key: "bid",
        multipleSelect: true,
        connector: ",",
      },
      {
        name: "中原",
        children: [
          {
            name: "不限",
            value: "",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "碧沙岗",
            value: "59",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "帝湖",
            value: "60",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "电力新村",
            value: "61",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "儿童公园",
            value: "62",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "交警二大队",
            value: "63",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "汽车西站",
            value: "64",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "热电厂",
            value: "65",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "桐柏北路",
            value: "66",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "万达广场",
            value: "67",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "五龙口",
            value: "68",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "五一公园",
            value: "69",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "西流湖",
            value: "70",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "月季公园",
            value: "71",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "郑州晚报社",
            value: "72",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "郑州一中",
            value: "73",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "郑州植物园",
            value: "913",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "绿城公园",
            value: "914",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "河南省直第三人民医院",
            value: "915",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "郑州市中原中医院",
            value: "916",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "锦艺城",
            value: "923",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
        ],
        value: "1",
        key: "did",
        child_key: "bid",
        multipleSelect: true,
        connector: ",",
      },
      {
        name: "郑东",
        children: [
          {
            name: "不限",
            value: "",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "龙子湖",
            value: "177",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "CBD",
            value: "51",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "黄河南路",
            value: "52",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "祭城",
            value: "53",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "天赋路",
            value: "54",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "通泰路",
            value: "55",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "新东站",
            value: "56",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "众意路",
            value: "57",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
        ],
        value: "12",
        key: "did",
        child_key: "bid",
        multipleSelect: true,
        connector: ",",
      },
      {
        name: "上街",
        children: [
          {
            name: "不限",
            value: "",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            name: "上街",
            value: "851",
            key: "bid",
            wechat_multipleSelect: true,
            connector: ",",
          },
        ],
        value: "22",
        key: "did",
        child_key: "bid",
        multipleSelect: true,
        connector: ",",
      },
    ],
  },
  {
    name: "地铁",
    key: "sid",
    children: [
      {
        key: "sid",
        name: "1号线",
        is_open: 1,
        multipleSelect: true,
        connector: ",",
        children: [
          {
            value: "1",
            key: "sid",
            is_open: 1,
            name: "河南工业大学",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "2",
            is_open: 1,
            name: "郑大科技园",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "3",
            is_open: 1,
            name: "郑州大学",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "4",
            is_open: 1,
            name: "梧桐街",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "5",
            is_open: 1,
            name: "兰寨",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "6",
            is_open: 1,
            name: "铁炉",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "7",
            is_open: 1,
            name: "市民中心",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "8",
            is_open: 1,
            name: "西流湖",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "9",
            is_open: 1,
            name: "西三环",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "10",
            is_open: 1,
            name: "秦岭路",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "11",
            is_open: 1,
            name: "五一公园",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "12",
            is_open: 1,
            name: "碧沙岗",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "13",
            is_open: 1,
            name: "绿城广场",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "14",
            is_open: 1,
            name: "医学院",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "15",
            is_open: 1,
            name: "郑州火车站",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "16",
            is_open: 1,
            name: "二七广场",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "17",
            is_open: 1,
            name: "人民路",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "18",
            is_open: 1,
            name: "紫荆山",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "19",
            is_open: 1,
            name: "燕庄",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "20",
            is_open: 1,
            name: "民航路",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "21",
            is_open: 1,
            name: "会展中心",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "22",
            is_open: 1,
            name: "黄河南路",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "23",
            is_open: 1,
            name: "农业南路",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "24",
            is_open: 1,
            name: "东风南路",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "25",
            is_open: 1,
            name: "郑州东站",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "26",
            is_open: 1,
            name: "博学路",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "27",
            is_open: 1,
            name: "市体育中心",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "28",
            is_open: 1,
            name: "龙子湖",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "29",
            is_open: 1,
            name: "文苑北路",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "30",
            is_open: 1,
            name: "河南大学新区",
            wechat_multipleSelect: true,
            connector: ",",
          },
        ],
      },
      {
        key: "sid",
        name: "2号线",
        is_open: 1,
        multipleSelect: true,
        connector: ",",
        children: [
          {
            value: "31",
            key: "sid",
            is_open: 1,
            name: "天山路",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "32",
            is_open: 1,
            name: "古树苑",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "33",
            is_open: 1,
            name: "金河路",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "34",
            is_open: 1,
            name: "黄河迎宾馆",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "35",
            is_open: 1,
            name: "田园路",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "36",
            is_open: 1,
            name: "金达街",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "37",
            is_open: 1,
            name: "刘庄",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "38",
            is_open: 1,
            name: "柳林",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "39",
            is_open: 1,
            name: "沙门",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "40",
            is_open: 1,
            name: "北三环",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "41",
            is_open: 1,
            name: "东风路",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "42",
            is_open: 1,
            name: "关虎屯",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "43",
            is_open: 1,
            name: "黄河路",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "44",
            is_open: 1,
            name: "紫荆山",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "45",
            is_open: 1,
            name: "东大街",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "46",
            is_open: 1,
            name: "陇海东路",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "47",
            is_open: 1,
            name: "二里岗",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "48",
            is_open: 1,
            name: "南五里堡",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "49",
            is_open: 1,
            name: "花寨",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "50",
            is_open: 1,
            name: "南三环",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "51",
            is_open: 1,
            name: "战马屯",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "52",
            is_open: 1,
            name: "南四环",
            wechat_multipleSelect: true,
            connector: ",",
          },
        ],
      },
      {
        key: "sid",
        name: "城郊线",
        is_open: 1,
        multipleSelect: true,
        connector: ",",
        children: [
          {
            value: "53",
            key: "sid",
            is_open: 1,
            name: "十八里河",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "54",
            is_open: 1,
            name: "沙窝里",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "55",
            is_open: 1,
            name: "双湖大道",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "56",
            is_open: 2,
            name: "小乔",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "57",
            is_open: 1,
            name: "华南城西",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "58",
            is_open: 1,
            name: "华南城",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "59",
            is_open: 2,
            name: "华南城东",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "60",
            is_open: 1,
            name: "孟庄",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "61",
            is_open: 2,
            name: "港区北",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "62",
            is_open: 1,
            name: "康平湖",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "63",
            is_open: 1,
            name: "兰河公园",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "64",
            is_open: 1,
            name: "恩平湖",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "65",
            is_open: 1,
            name: "综合保税区",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "66",
            is_open: 1,
            name: "新郑机场",
            wechat_multipleSelect: true,
            connector: ",",
          },
        ],
      },
      {
        key: "sid",
        name: "3号线(在建)",
        is_open: 2,
        multipleSelect: true,
        connector: ",",
        children: [
          {
            value: "67",
            key: "sid",
            is_open: 2,
            name: "省体育中心",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "68",
            is_open: 2,
            name: "国基路",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "69",
            is_open: 2,
            name: "兴隆铺路",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "70",
            is_open: 2,
            name: "同乐",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "71",
            is_open: 2,
            name: "农业路",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "72",
            is_open: 2,
            name: "海滩寺",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "73",
            is_open: 2,
            name: "大石桥",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "74",
            is_open: 2,
            name: "大康路",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "75",
            is_open: 2,
            name: "二七广场",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "76",
            is_open: 2,
            name: "顺城街",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "77",
            is_open: 2,
            name: "东大街",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "78",
            is_open: 2,
            name: "城东路",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "79",
            is_open: 2,
            name: "博览中心",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "80",
            is_open: 2,
            name: "凤台路",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "81",
            is_open: 2,
            name: "中州大道",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "82",
            is_open: 2,
            name: "通泰路",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "83",
            is_open: 2,
            name: "黄河南路",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "84",
            is_open: 2,
            name: "农业南路",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "85",
            is_open: 2,
            name: "省骨科医院",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "86",
            is_open: 2,
            name: "博学路",
            wechat_multipleSelect: true,
            connector: ",",
          },
        ],
      },
      {
        key: "sid",
        name: "4号线(在建)",
        is_open: 2,
        multipleSelect: true,
        connector: ",",
        children: [
          {
            value: "87",
            key: "sid",
            is_open: 2,
            name: "安顺路",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "88",
            is_open: 2,
            name: "省体育中心",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "89",
            is_open: 2,
            name: "二十里铺",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "90",
            is_open: 2,
            name: "丰庆路",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "91",
            is_open: 2,
            name: "张家村",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "92",
            is_open: 2,
            name: "西沙路",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "93",
            is_open: 2,
            name: "沙门",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "94",
            is_open: 2,
            name: "龙源一街",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "95",
            is_open: 2,
            name: "龙源五街",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "96",
            is_open: 2,
            name: "龙湖北站",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "97",
            is_open: 2,
            name: "龙湖十一街",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "98",
            is_open: 2,
            name: "龙湖内环路",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "99",
            is_open: 2,
            name: "龙湖岛",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "100",
            is_open: 2,
            name: "副CBD内环",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "101",
            is_open: 2,
            name: "鑫融街",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "102",
            is_open: 2,
            name: "龙湖中环路",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "103",
            is_open: 2,
            name: "农业东路",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "104",
            is_open: 2,
            name: "中央商务区",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "105",
            is_open: 2,
            name: "会展中心",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "106",
            is_open: 2,
            name: "商鼎路",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "107",
            is_open: 2,
            name: "中州大道",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "108",
            is_open: 2,
            name: "货栈街",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "109",
            is_open: 2,
            name: "七里河",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "110",
            is_open: 2,
            name: "果园路",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "111",
            is_open: 2,
            name: "太白路",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "112",
            is_open: 2,
            name: "星火路",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "113",
            is_open: 2,
            name: "河西北路",
            wechat_multipleSelect: true,
            connector: ",",
          },
        ],
      },
      {
        key: "sid",
        name: "5号线",
        is_open: 1,
        multipleSelect: true,
        connector: ",",
        children: [
          {
            value: "114",
            key: "sid",
            is_open: 1,
            name: "沙口路",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "115",
            is_open: 1,
            name: "月季公园",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "116",
            is_open: 1,
            name: "五一公园",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "117",
            is_open: 1,
            name: "市中心医院",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "118",
            is_open: 1,
            name: "陇海西路",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "119",
            is_open: 1,
            name: "桐淮",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "120",
            is_open: 1,
            name: "后河芦",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "121",
            is_open: 1,
            name: "齐礼阁",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "122",
            is_open: 1,
            name: "市第二人民医院",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "123",
            is_open: 1,
            name: "京广南路",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "124",
            is_open: 1,
            name: "冯庄",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "125",
            is_open: 1,
            name: "南五里堡",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "126",
            is_open: 1,
            name: "城东南路",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "127",
            is_open: 1,
            name: "航海广场",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "128",
            is_open: 1,
            name: "七里河",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "129",
            is_open: 1,
            name: "中原福塔",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "130",
            is_open: 1,
            name: "福塔东",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "131",
            is_open: 1,
            name: "经开中心广场",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "132",
            is_open: 1,
            name: "经北二路",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "133",
            is_open: 1,
            name: "省骨科医院",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "134",
            is_open: 1,
            name: "康宁街",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "135",
            is_open: 1,
            name: "郑州东站",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "136",
            is_open: 1,
            name: "金水东路",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "137",
            is_open: 1,
            name: "祭城",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "138",
            is_open: 1,
            name: "儿童医院",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "139",
            is_open: 1,
            name: "中央商务区",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "140",
            is_open: 1,
            name: "众意西路",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "141",
            is_open: 1,
            name: "姚砦",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "142",
            is_open: 1,
            name: "省人民医院",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "143",
            is_open: 1,
            name: "黄河路",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "144",
            is_open: 1,
            name: "郑州人民医院",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "145",
            is_open: 1,
            name: "海滩寺",
            wechat_multipleSelect: true,
            connector: ",",
          },
        ],
      },
      {
        key: "sid",
        name: "6号线(在建)",
        is_open: 2,
        multipleSelect: true,
        connector: ",",
        children: [
          {
            value: "146",
            key: "sid",
            is_open: 2,
            name: "贾峪镇",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "147",
            is_open: 2,
            name: "湿地公园",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "148",
            is_open: 2,
            name: "洞林湖",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "149",
            is_open: 2,
            name: "安宁路",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "150",
            is_open: 2,
            name: "光明路",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "151",
            is_open: 2,
            name: "工业路",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "152",
            is_open: 2,
            name: "金马路",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "153",
            is_open: 2,
            name: "泉州路",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "154",
            is_open: 2,
            name: "奥体中心",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "155",
            is_open: 2,
            name: "林湖路",
            wechat_multipleSelect: true,
            connector: ",",
          },
        ],
      },
      {
        key: "sid",
        name: "10号线(在建)",
        is_open: 2,
        multipleSelect: true,
        connector: ",",
        children: [
          {
            value: "156",
            key: "sid",
            is_open: 2,
            name: "东虢湖站",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "157",
            is_open: 2,
            name: "上街铝厂",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "158",
            is_open: 2,
            name: "峡窝站",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "159",
            is_open: 2,
            name: "玉发大道",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "160",
            is_open: 2,
            name: "金华路",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "161",
            is_open: 2,
            name: "杨桐站",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "162",
            is_open: 2,
            name: "荥阳中医院",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "163",
            is_open: 2,
            name: "畅园站",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "164",
            is_open: 2,
            name: "荥阳植物园",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "165",
            is_open: 2,
            name: "禹锡园",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "166",
            is_open: 2,
            name: "郑州西站",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "167",
            is_open: 2,
            name: "商隐路",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "168",
            is_open: 2,
            name: "庙王村",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "169",
            is_open: 2,
            name: "须水",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "170",
            is_open: 2,
            name: "市委党校",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "171",
            is_open: 2,
            name: "郑州一中",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "172",
            is_open: 2,
            name: "杏树塆",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "173",
            is_open: 2,
            name: "二砂",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "174",
            is_open: 2,
            name: "市中心医院",
            wechat_multipleSelect: true,
            connector: ",",
          },
        ],
      },
      {
        key: "sid",
        name: "14号线",
        is_open: 1,
        multipleSelect: true,
        connector: ",",
        children: [
          {
            value: "175",
            key: "sid",
            is_open: 1,
            name: "须水",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "176",
            is_open: 1,
            name: "铁炉",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "177",
            is_open: 1,
            name: "市民大道",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "178",
            is_open: 1,
            name: "市委党校",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "179",
            is_open: 1,
            name: "奥体中心",
            wechat_multipleSelect: true,
            connector: ",",
          },
          {
            key: "sid",
            value: "180",
            is_open: 1,
            name: "莲湖",
            wechat_multipleSelect: true,
            connector: ",",
          },
        ],
      },
    ],
  },
  {
    name: "附近",
    key: "near_distance",
    children: [
      { name: "不限", value: "", key: "near_distance" },
      { name: "1km内", value: "1000", key: "near_distance" },
      { name: "2km内", value: "2000", key: "near_distance" },
      { name: "5km内", value: "5000", key: "near_distance" },
    ],
  },
];

export default data;
